services:
    
  fabric:
    image: osioaliu/fabric:latest
    build:
      context: ./.docker/fabric
      args:
        GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    container_name: fabric
    pull_policy: always
    env_file:
      - .env
    ports:
      - "9090:8080"
    working_dir: /go/bin
    volumes:
      - ./.env:/root/.config/fabric/.env
      - ~/fabric:/go/bin/output
